### ISSUE TITLE
Strategy for simulation of NeuroML in python.  

### ISSUE THREAD

**Issue by rgerkin** [NeuroML/pyNeuroML#1]
@pgleeson In what you have here so far, you created a function that calls jnml directly, i.e. ```run_jnml``` [here](https://github.com/pgleeson/pyNeuroML/blob/master/pynml/pynml.py).  

Alternatively, one could go through pylems, which my [pull request](https://github.com/LEMS/pylems/pull/22) (specifically [this](https://github.com/LEMS/pylems/commit/ed435e240751c2c1e162ae689a1af66183ffd914)) allows.  

You're approach looks like it has the beginnings of simulator independence.  It also uses jNeuroML instead of pylems, and I'm actually unclear as to where the boundaries of jNeuroML and py/jLems are in terms of what they are meant to simulate.  Do you think there is any value to a pure-ish (at least, no Java) python approach?  Any clarity would be appreciated.

**Comment by pgleeson** [comment]
The goals/scope/functionality of pyneuroml are still in development... Sorry if it looks like the best place to get some features you need and they're not there yet; they will be but it will just take some time to get everything together. For now it's best to work with your own solutions and when something works here I'll update it in some of the test scripts in other modules and let you know.

A key motivation for this package is that there are so many features in jnml that are much more stable than pylems (and may never be implemented in pure python...) and it would be good to get access to these from python. This may require some updates to jNeuroML too. Pylems needs a lot of work to get it as robust, so best not pin your hopes on getting everything working with that yet...

Pyneuroml is high on my list of todos for next week...

**Comment by pgleeson** [comment]
@rgerkin hope the scope of PyNeuroML is clear now...
