### ISSUE TITLE
Replace `print_comment*` methods with a logging class implementation

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#106]
https://docs.python.org/3/library/logging.html?highlight=logger

This is quite straightforward to use, and allows easy toggling of debug/warning/error/info etc. levels of verbosity.

Should be a straightforward task too.

**Comment by pgleeson** [comment]
True, but the same simple scheme is used in NeuroMLlite, OMV...

**Comment by sanjayankur31** [comment]
I can move them over one by one later, not urgent at all
