### ISSUE TITLE
Expose programmatic access to error messages

### ISSUE THREAD

**Issue by jonrkarr** [NeuroML/pyNeuroML#126]
Its hard to retrieve those messages programmatically since they are printed to the console.

**Describe the solution you'd like**
Expose programmatic access to the messages, ideally a list of errors and warnings

**Describe alternatives you've considered**
Programmatically collecting console output, such as using [capturer](https://pypi.org/project/capturer/) or subprocess.

**Comment by jonrkarr** [comment]
Alternatively, if a different library does this (e.g., libNeuroML), we'd be happy to use that.

**Comment by sanjayankur31** [comment]
@jonrkarr : could you please take a quick look to see if #127 works for your use case?
