### ISSUE TITLE
Unable to install pyneuroml using pip

### ISSUE THREAD

**Issue by wvangeit** [NeuroML/pyNeuroML#13]
When running:
'pip install pyneuroml'

The following error is generated:
"Collecting airspeed>=0.4.1 (from pyneuroml)
  Could not find a version that satisfies the requirement airspeed>=0.4.1 (from pyneuroml) (from versions: 0.5.3dev-20150421.macosx-10.10-x86_64, 0.5.4dev-20150515.macosx-10.10-x86_64, 0.2.dev20131105, 0.4.dev20131106, 0.4.1.dev20131108, 0.4.2.dev20131111, 0.5.1.dev20150215, 0.5.2.dev20150216, 0.5.3.dev20150421, 0.5.4.dev20150515)
No matching distribution found for airspeed>=0.4.1 (from pyneuroml)"

This  can atm manually be solved by executing 'pip install airspeed'
Then:
Collecting libNeuroML>=0.2.5 (from pyneuroml)
  Could not find a version that satisfies the requirement libNeuroML>=0.2.5 (from pyneuroml) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.9.1)
No matching distribution found for libNeuroML>=0.2.5 (from pyneuroml)

Which again atm can be solved by cloning the libNeuroML repo, and switching to the development branch.

Ideally the pyneuroml pypi package should be updated.

**Comment by pgleeson** [comment]
Could you try if you get a chance with:

    git clone https://github.com/NeuroML/pyNeuroML.git
    cd pyNeuroML
    sudo pip install . -r requirements.txt

**Comment by wvangeit** [comment]
Yep, that seems to work. 
Although 'pip install pyneuroml' still doesn't work.

**Comment by souravsingh** [comment]
I tried installing pyNeuroML using a virtualenv and it showed the same error as mentioned by @wvangeit

**Comment by souravsingh** [comment]
I have tried installing airspeed and libNeuroML individually via ````pip install`````and they work pretty nicely.

**Comment by souravsingh** [comment]
The version of airspeed is ````0.5.4```` and libNeuroML is ````0.2.11````

**Comment by pgleeson** [comment]
So have you managed to get pyNeuroML installed and working following manual install of airspeed/libNeruoML @souravsingh?

**Comment by souravsingh** [comment]
@pgleeson I have managed to get pyNeuroML installed and working after manually installing airspeed and libNeuroML.

**Comment by pgleeson** [comment]
@wvangeit I believe I solved the issue with airspeed (https://github.com/NeuroML/pyNeuroML/commit/489ae90d049faea46ebebcaeed3f99607258ae30), and 

    pip install pyneuroml

should work fine now. Let me know if you have any more problems.

**Comment by wvangeit** [comment]
Just tried it. Works indeed. Thanks.
