### ISSUE TITLE
Add `-swc` option to export NeuroML cell files to SWC format

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#133]
This is already implemented in the `pyneuroml.swc` package, so it just just needs to be exposed.

**Comment by YBCS** [comment]
@sanjayankur31 is this still open ?

**Comment by pgleeson** [comment]
@YBCS Yes, I believe it is.

**Comment by YBCS** [comment]
@pgleeson can I work on this

**Comment by sanjayankur31** [comment]
Great, I've assigned it to you now.

**Comment by YBCS** [comment]
Hi @sanjayankur31 , I am getting this error, do you have any idea what is going on here ?

![image](https://github.com/NeuroML/pyNeuroML/assets/29734619/d7ede252-f763-4489-9bfc-c3b708ba3fcd)

I am using a virtual env
in my terminal if I simply start a python REPL and run 
`import lems.model.model as lems_model`
`import lems`
there is no error but if I run the command `python pyneuroml/pynml.py`, then the error comes up 
Is it conflicting with `pyneuroml/lems`.

**Comment by sanjayankur31** [comment]
Hrm, it shouldn't. One doesn't run `pynml.py` because it's not a script to be run, it's a module. We run `pynml` which is a terminal command created from modules in `pynml.py` etc. So, once you've run `pip install -e .` you'll have `pynml` available as a command. See setup.cfg for the entry points.

**Comment by YBCS** [comment]
@sanjayankur31 thanks for the clarification I have a raised a PR for the same.
