### ISSUE TITLE
[Bug] Brian2 simulation function produces space-separated results rather than tab-separated results

### ISSUE THREAD

**Issue by jonrkarr** [NeuroML/pyNeuroML#138]
**Describe the bug**
Different simulation methods output results in different formats. It would be helpful to be consistent.

**To Reproduce**
Run simulations with jNeuroML and Brian2

**Expected behavior**
Use consistent separators

**Observed behavior**
Different separators:
- jNeuroML: tabs
- Brian2: spaces

**System information:**
 - OS: [e.g. iOS]: Ubuntu 20
 - Python version (`python --version`): 3.9.5
 - Version of tools in use  (`pynml --help`): pyNeuroML 0.5.18, Brian2 2.4.2

**Comment by pgleeson** [comment]
Fixed in latest release
