### ISSUE TITLE
Manage or document additional requirements for other simulation tools

### ISSUE THREAD

**Issue by jonrkarr** [NeuroML/pyNeuroML#141]
These optional dependencies could be managed with the `extras_require` argument to `setuptools.setup` or documented.

## Neuron
Executing simulations with NEURON also requires the NEURON and the ability to compile NEURON mod files. 

Requirement for Ubuntu:
- `neuron` Python package
- `gcc`
- `g++` 
- `make`

Executing NEURON in a headless environment also requires xvfb

## NetPyNe
Requires the `netpyne` Python package, the requirements for NEURON, and
- `mpi`
- `libmpich-dev`

## Brian 2
Requires the `brian2` Python package

**Comment by sanjayankur31** [comment]
We can add the extra requirements, but I'm not aware of a way of getting pip to install g++ and MPI. Folks have to set that up themselves using whatever package manager they wish---either system package managers (apt/dnf/brew) or whatever else they use: conda/mamba and so on.

**Comment by sanjayankur31** [comment]
Also added some information on this to the docs:

https://github.com/NeuroML/Documentation/commit/e53c5c357c817769f6eff8cc2ac5ec1c369b25f9

**Comment by jonrkarr** [comment]
Sorry the issue could have been clearer. 

Brian could be an optional dependency for the python package. 

Agreed, NEURON and NetPyNe require more dependencies. I suggest documenting these rather than trying to manage their instantallation.

**Comment by sanjayankur31** [comment]
I've added the python packages as extras, and briefly documented that NEURON etc. may require additional bits:

https://docs.neuroml.org/Userdocs/Software/pyNeuroML.html#install-pyneuroml-with-pip
