### ISSUE TITLE
pynml -validate *nml doesn't validate all *nml files at once

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/pyNeuroML#166]
`jnml -validate *nml` will validate all *nml files in the present dir (and provide a brief summary), but `pynml -validate *nml` will run jnml N times, once for each of the N *nml files.

**Comment by sanjayankur31** [comment]
Note that we can now validate models against the schema *without* needing jnml (using the `validate()` methods that we've added to each component type python class). We need to migrate the extra tests over from jnml. This is WIP here: https://github.com/NeuralEnsemble/libNeuroML/pull/156

**Comment by pgleeson** [comment]
Closing as original issue fixed
