### ISSUE TITLE
Running a simulation with default options requires internet connectivity

### ISSUE THREAD

**Issue by epiasini** [NeuroML/pyNeuroML#2]
The [`write_lems_file`](https://github.com/NeuroML/pyNeuroML/blob/5626cc78c48dc7c3f0ef38a0e21cf0d74288e252/pyneuroml/pynml.py#L93-L99) function, by default, calls the [`validate_lems`](https://github.com/LEMS/pylems/blob/d340915953433e5d190efffa5eb5f0862a6a7eff/lems/base/util.py#L47-L59) function from pylems after writing the file to disk. But `validate_lems` always fetches the latest version of the LEMS schema available online, and it fails in absence of internet connectivity!

I guess the default value of the `validate` argument to `write_lems_file` should be set to `False`.

(cc @caycogajic, @pgleeson)

**Comment by pgleeson** [comment]
Ok, done.
