### ISSUE TITLE
pynml-modchananalysis: allow saving of plots without user intervention (for batch processing)

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#201]
At the moment, if one uses `-nogui`, only the data files are stored but the figures (which are generated) are just discarded. Ideally, when a user says `-nogui` the data *and* the figure files should be saved. This will allow batch processing where I can run `pynml-modchananalsyis *` on a bunch of files and just let it run. At the moment, the graphs are generated and users have to manually save them to file.

**Comment by YBCS** [comment]
@sanjayankur31 can I work on this

**Comment by sanjayankur31** [comment]
Sure, assigned to you now

@YBCS : please do start working on your proposal for GSoC if you haven't already. We'll be able to give you feedback by wednesday evening. (We have Friday and Monday as holidays here, so we wont be working from Friday until Tuesday)
