### ISSUE TITLE
mview_neuroml2.hoc docs not create default soma, dendrite, axonal groups

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#204]
Should it also create these, or is the user expected to add them later after the initial export?

**Comment by pgleeson** [comment]
Hmm, these are by no means compulsory, so it would be a bit strange to add them and leave them empty. Also automatically filling them could be problematic, sections named dend123 would be fine but you'd have to catch all the apical, basal, oblique, tuft naming possibilities too. Best to just export what's known to be present inside Neuron and leave the user to add extra info.

**Comment by sanjayankur31** [comment]
Sounds good. Maybe we print a user message that sort of provides a report of the conversion, just using "cell.morphinfo()" so they know how many segment groups and segments were created?
