### ISSUE TITLE
Suggested updates to 2D plots etc

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/pyNeuroML#220]
From changes in https://github.com/NeuroML/pyNeuroML/pull/213

- [ ] 2D plots should be `-plotType Detailed` by default, as they will generally not be too large, and it's more natural to want to see diams also.
- [x] Why are "Detailed, Constant, or Schematic" with caps? Lowercase more pythonic?
- [x] theme='dark' not supported in 2D plots. Not very likely to be used much, but the command line arguments suggest it is an option...

**Comment by sanjayankur31** [comment]
- the plottype option is shared between 2d and 3d plotter, so if I change the default for 2d, it'll also change for 3d. Leaving it as is for the moment.
- for the theme, I've improved the option doc to say that it is unused for 2d plotting at the moment.
