### ISSUE TITLE
Generate API documentation and add to RTD

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/pyNeuroML#25]
Can be based on what's used for libNeuroML: https://github.com/NeuralEnsemble/libNeuroML/tree/master/doc

**Comment by rgerkin** [comment]
@pgleeson If you just want to get started with Sphinx auto-generated API documentation, hosted on readthedocs, and then want to add more human-readable documentation as you go, I can help with that.

**Comment by sanjayankur31** [comment]
I've been tinkering with this, but the sphinx autodoc extension fails for me at the moment. I'll keep looking to see what we can manage. It will certainly be nice to have RTD docs for pyneuroml also. Not assigining to myself in case someone else wants to work on this.

**Comment by rgerkin** [comment]
I switched to Jupyter Book for a recent project.  Write all your docs as notebooks and never have to think about Sphinx again (although it does use Sphinx to compile to html).

**Comment by sanjayankur31** [comment]
We use jupyter-notebooks for the primary neuroml documentation at docs.neuroml.org where we lots of manual documentation and notebooks. These libraries need API documentation (on RTD?), though, for which we need sphinx-autodoc.

**Comment by rgerkin** [comment]
I have something similar, where my main documentation site (built from Jupyter Book) has a link to the RTFD site which only builds my API docs and nothing else.

**Comment by sanjayankur31** [comment]
This is now live for the `development` branch, and will go live for others once we merge it to `master`:

https://pyneuroml.readthedocs.io/en/development/
