### ISSUE TITLE
Add option to validate SBML 

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/pyNeuroML#250]
e.g. `pynml -validate-sbml MyModel.sbml`

Will probably involve a call to libsbml, e.g. see under 3) here: https://github.com/combine-org/combine-notebooks/blob/main/notebooks/sbml.ipynb

Command line option could be added like this: 
https://github.com/NeuroML/pyNeuroML/blob/3af5ab2e7bc25d2de2282b246ef9610efa4d8130/pyneuroml/pynml.py#L325-L329

probably calling a dedicated method in a new module sbml under: https://github.com/NeuroML/pyNeuroML/tree/master/pyneuroml

FYI @robertvi

**Comment by robertvi** [comment]
I've created a fork to work on this, starting from the development branch:
https://github.com/robertvi/pyNeuroML/tree/development

**Comment by robertvi** [comment]
https://github.com/NeuroML/pyNeuroML/pull/266 created a draft pull request

**Comment by pgleeson** [comment]
Done
