### ISSUE TITLE
Add option to validate SED-ML files

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/pyNeuroML#277]
Similar to https://github.com/NeuroML/pyNeuroML/issues/250

See https://github.com/fbergmann/libSEDML/blob/59db0be6ece97604c31abb76fdd5641756f2c8de/examples/python/validate.py#L8

Also https://github.com/combine-org/combine-notebooks/blob/main/notebooks/sedml.ipynb

FYI @robertvi

**Comment by YBCS** [comment]
@sanjayankur31 can I work on this

**Comment by pgleeson** [comment]
Sorry @YBCS, should have closed this, it has been done: https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/sedml/__init__.py
