### ISSUE TITLE
Issue compiling .mod files on Apple Silicon [Bug]

### ISSUE THREAD

**Issue by olitr20** [NeuroML/pyNeuroML#293]
**Describe the bug**
Failure to compile .mod files in the working directory when running jneuroml

**To Reproduce**
run_lems_with_jneuroml_neuron(lems_simulation_file, max_memory="2G", plot=False)

**Expected behavior**
Command will complete successfully, compiling all .mod files and returning simulation output.

**Observed behavior**
(INFO) NMODL Error   >> > make: [/Users/heeren/source/github/neuronsimulator/nrn/build/cmake_install/bin/nrnmech_makefile]: No such file or directory
(INFO) NMODL Error   >> > make: *** No rule to make target `/Users/heeren/source/github/neuronsimulator/nrn/build/cmake_install/bin/nrnmech_makefile'.  Stop.

**System information:**
 - OS: MacOS Sonoma 14.2 running on Apple M2
 - Python 3.11.3
 - pyNeuroML v1.1.10 (libNeuroML v0.5.7, jNeuroML v0.13.0)

**Comment by pgleeson** [comment]
Hi @olitr20,
I have jnml successfully compiling mod files on M2 silicon, and we've made sure that functionality is in the released version.
My first guess is that not all the libraries are present for compiling mod files. Can you run `nrnivmodl` successfully in a directory containing mod files? 
You also seem to have Nrn built from source. Any special reason/requirement for that? 
For my environment, I have a dedicated conda env and nrn v8.1 pip installed.

**Comment by pgleeson** [comment]
Hi @olitr20, yes, it's definitely a requirement to have NEURON_HOME set to the correct location to jnml can find the nrnivmodl executable (in NEURON_HOME/bin/nrnivmodl), and this should be set as an environment variable that the jnml process can see (so should be present before you start jupyter-lab or however you run your notebooks). Try also at command line with running `pynml MyLEMS.xml -neuron -run -nogui` to make sure it can find the correct location.

**Comment by sanjayankur31** [comment]
Hi @olitr20 , how is it going? Were you able to fix this issue, or is there something that the NeuroML dev team needs to look into? Please do let us know.

**Comment by olitr20** [comment]
Hi, all fixed now - thank you!
