### ISSUE TITLE
Add dependencies to installation manual

### ISSUE THREAD

**Issue by VahidGh** [NeuroML/pyNeuroML#3]
when running `pynml-channelanalysis` getting errors about importing from pyelectro, scipy, etc. 
Could you please add needed dependencies to the installation manual.

**Comment by pgleeson** [comment]
@VahidGh, this should be resolved in the latest commit. There were some imports which were called at the top level when they were only needed in specific functions.

pynml-channelanalysis should work now without these.

**Comment by VahidGh** [comment]
Solved, thanks.
