### ISSUE TITLE
Refactor: de-duplicate PlotSpikes code

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#303]
We've got code that plots spikes in the PlotSpikes module, but also in the runners.reload_data function. We should de-duplicate these. Ideally, the PlotSpikes model should take the data, or list of text files to be a general spike plotting function, and the re-load data could read LEMS files to figure out the data files and then use PlotSpikes. 

Similarly, runners.reload_data also includes functionality to plot traces. This should be split out into a different module "PlotTimeSeries" or something, and then reload_data should re-use it.

**Comment by AdityaBITMESRA** [comment]
Hello sir, I would like to work on this issue. Can you please guide me on how should I proceed with it?

**Comment by AdityaBITMESRA** [comment]
Thanks for the guidance...I will start following it

**Comment by AdityaBITMESRA** [comment]
I have added a PR, can you please review my code
