### ISSUE TITLE
[vispy viewer] align cells along its first principal component

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#317]
NeuroML-DB does this to generate the GIFs so we should follow suit and do the same. 

> To visualize it, each cell model’s morphology was first aligned along its first principal
component and a 360˚ view of the model is shown from a slightly tilted, horizontal orbit.

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010941

**Comment by lej0hn** [comment]
Hello! Could you please clarify the goal a bit as I am not sure I understood it precisely. Is it to be able to create something like the gifs in NeuroML-DB, like this for example https://neuroml-db.org/model_info?model_id=NMLCL000491 for individual  cells?

**Comment by sanjayankur31** [comment]
When looking at individual cells, we could re-orient them to look "upright", similar to how it's done in NeuroML-DB. (When looking at networks, we don't do this because there, all cells will have their own orientations and we don't want to change that).

**Comment by lej0hn** [comment]
Ok I see, I would like to start working on this
