### ISSUE TITLE
Implement vispy based viewing of SWC files

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#362]
This will be useful for users to visualise unconverted SWC files, and to then compare the visualisations with the NeuroML conversions.

**Comment by pgleeson** [comment]
Don't forget that OSBv1 can visualise SWC files: https://v1.opensourcebrain.org/projects/neuromorpho/models

Also, the "definitive" version of an SWC viewer is here;:https://github.com/pgleeson/Cvapp-NeuroMorpho.org

**Comment by sanjayankur31** [comment]
Implemented in https://github.com/NeuroML/pyNeuroML/commit/3d9a27f0210b8f4cb7ecc6881f753749af4635a9

We first export the SWC to NeuroML and then visualise it.
