### ISSUE TITLE
Branches for pip versions

### ISSUE THREAD

**Issue by rgerkin** [NeuroML/pyNeuroML#37]
I'd like to be able to pip install pyneuroml as a requirement for my other packages, but I don't usually know what commit the pip version corresponds to and have to work it by diff.  Next time you release on pip could you tag that version here, or create a branch for it?  TBH this is something I need to do in my own packages as well.

**Comment by pgleeson** [comment]
Why do you need to go to to github at all? If it's a stable release, it will be on PyPI, so you can just use:

    pip install libneuroml==0.2.30

If you do need the very latest version, just get the development branch and install from there.

That said, it can't hurt to tag the releases as they get uploaded to PyPI, so I'll try to do that too.

**Comment by pgleeson** [comment]
Have made this: https://github.com/NeuroML/pyNeuroML/releases/tag/v0.3.4 & will try to tag when I upload versions...
