### ISSUE TITLE
Add a SWC loader

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#375]
A loader for SWC files that then allows us to query the various fields would be useful as a first step.

https://github.com/pgleeson/Cvapp-NeuroMorpho.org?tab=readme-ov-file is the reference implementation used on neuromorpho.org, so the first task would be to:

- [x] download and install this
- [x] test it out with a few SWC files from neuromorpho.org to get a feel for how it all works

Then, adding a module that will:

- [x] load a SWC file 
- [x] parse the file into a data structure for us to hold in memory

The data structure can evolve as we go, so just a simple class for the moment will do.

References:

- https://swc-specification.readthedocs.io/en/latest/swc.html
- https://neuromorpho.org/myfaq.jsp

Also worth having a look at to see how they do it: 

- https://morphio.readthedocs.io/en/latest/python.html#morphio.Morphology 
- https://neurom.readthedocs.io/en/stable/index.html

**Comment by AdityaBITMESRA** [comment]
Thankyou for this

**Comment by AdityaBITMESRA** [comment]
Sure
