### ISSUE TITLE
Exception running long-lasting c302/tuner optimizations

### ISSUE THREAD

**Issue by lungd** [NeuroML/pyNeuroML#38]
I got an exception (https://github.com/NeuroML/pyNeuroML/blob/master/pyneuroml/pynml.py#L662) while running the optimizer for several hours.
As workaround I commented out the raise of that exception. Ofc this is not a good idea but I did not find the source of the issue and for the optimizer it works.

@pgleeson, can you say something about this issue?

**Comment by pgleeson** [comment]
The filename refers to the data file produced by the LEMS/Neuron simulation, and this should have a timestamp after the point which the simulation was set running. If you're getting this exception, what is probably happening is that the simulation is failing, and it's reloading the data file from the the last time the simulation was successfully run, which probably used a different set of parameters. 

I'd suggest putting back in the Exception, and trying to get to the root of the issue. You can try directly running the Neuron files (*nrn.py) which were produced to see what the output is.

**Comment by lungd** [comment]
I got the exception again after ~1h. 
Exception: Expected output file NT_AVB_DBAVB_DB_Tue_Jun__6_16.56.35_2017//CANDIDATE_0/AVB_DBAVB_DB.dat has not been modified since 2017-06-06 17:50:10.162064 but the simulation was run later at 2017-06-06 17:51:37.846775.
But no error with `python *nrn.py`. I run it from inside CANDIDATE_0/.

I am going to do some debugging, but at the moment I am not really sure where to begin.
However, I guess this issue is not related to pyNeuroML.

**Comment by lungd** [comment]
https://github.com/lungd/CElegansNeuroML/blob/5b8bab774b58685e49a2b574fae9caddf64af62b/CElegans/pythonScripts/c302/tune/C302Controller.py#L137
I was assuming that calling job() for the first time just waits until the result is available and then calling job() a second time returns the result. Now I think I was wrong.
I didn't get the exception with only one job() call, but I am still testing.

@pgleeson, I think you can close this issue. If I run into this problem again, I can open a new issue in CElegansNeuroML.

**Comment by pgleeson** [comment]
Ok.
