### ISSUE TITLE
Add SWC exporter

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#403]
A new file in the swc module called "ExportNML.py" for this. Your function will take a SWCGraph as an argument and then convert it to NeuroML.

The logic behind keeping this separate and not including it into the LoadSWC module is to keep the LoadSWC file independent of NeuroML

**Comment by AdityaBITMESRA** [comment]
Will start working on this

**Comment by sanjayankur31** [comment]
See also: https://libneuroml.readthedocs.io/en/development/userdocs/coreclasses.html#neuroml.nml.nml.Cell.add_unbranched_segments

- before saving to the file, validate the morphology: `cell.morphologies[0].validate()` should do it.
- quick summary: `pynml-summary <cell file> -v`; `cell.morphinfo()` should also provide some information
