### ISSUE TITLE
Making reloading of data more flexible

### ISSUE THREAD

**Issue by rgerkin** [NeuroML/pyNeuroML#41]
For parallel processing I started executing in temporary directories (numbered by processor core, for example), which means that the location of the LEMS file (which is fixed) varies relative to the location of the file where I want the output to be written (which will be different for each core).  As I see it, the call to `reload_saved_data` as currently written (e.g. for [run with jNeuroML](https://github.com/NeuroML/pyNeuroML/blob/master/pyneuroml/pynml.py#L474) but it's the same for NEURON) requires a fixed relationship because the `relative_path` function assumes that `exec_in_dir`and `lems_file_name` will have a fixed relationship.  

I addressed this in uncommitted code by changing the signature of reload_saved_data to take the `exec_in_dir` path and the `lems_file` path as two separate arguments, and by making upstream functions responsible for providing a `lems_file` path that resolves to a file on disk that may or may not have anything to do with `exec_in_dir`.  

I want to check whether you have any reason to believe this will cause problems with other parts of the package or other use cases before I commit and pull request this.

**Comment by pgleeson** [comment]
@rgerkin This sounds fine as long as everything else still works...

I had some changes in the development branch (still intend to do most work on master) which I've just merged, which relate to path handling. You'll want to test with these changes.

**Comment by rgerkin** [comment]
Implemented in #43.

**Comment by pgleeson** [comment]
Believe this is done...
