### ISSUE TITLE
Morphology plotting: handle cells where morphology is a standalone element that is referenced in cell

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#414]
It looks like we don't handle this case at the moment. The morphology file needs to be loaded here.

**Comment by pgleeson** [comment]
See if fix_external_morphs_biophys solves this...
https://github.com/NeuroML/pyNeuroML/commit/1622a4290e359fe91a5150acb6a212cd96e78c10

**Comment by pgleeson** [comment]
Just saw your PR...

**Comment by sanjayankur31** [comment]
It sort of does, but it doesn't load bits from included files. Seeing if I can tweak it to do that too.
