### ISSUE TITLE
pyNeuroML and Macports Python install issue

### ISSUE THREAD

**Issue by espenhgn** [NeuroML/pyNeuroML#44]
Hi, 
I tried installing pyNeuroML on my machine (macOS Sierra 10.12.6) on which I've set up Python 2.7.13 using macports (https://www.macports.org), but there is a couple of issues. Macports installs everything in a self-contained tree under `/opt/local`.

As for installing pyNeuroML, the main installation works fine either using pip or from source except that the `pynml*` executables are not linked in the default `/opt/local/bin/` folder (which macports adds to the PATH upon installation), but only ends up in a folder `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/` (which is correct still, but not in the default PATH). So symlinks should be made in `/opt/local/bin`. 

The second issue is file permissions. The `pynml*` files have permission `-rwx------` but should be `-rwxr-xr-x`. I'm thus curious whether or not this is a known issue, that may or may not have an easy fix (except manually fixing the install).

**Comment by espenhgn** [comment]
Looked into this issue a bit again, and it appears to be a known issue with macports (https://trac.macports.org/ticket/50058 and https://github.com/pypa/pip/issues/113). The problem is that `pip` installs by default to the path returned by `sysconfig.get_path('scripts')`, which on my machine is `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin`. 

It seems like the "safe" solution is to create an virtual env with `pip` installed from source. 
Alternatively, one could provide a Portfile, and would allow "selecting" the correctly installed `pynml` with `sudo port select --set pyneuroml py27-pyneuroml` for example (in order to create the missing symlinks). Would that be of interest?

**Comment by espenhgn** [comment]
Hmm. Maybe this was a non-issue for others due to some configuration issue on my machine. I renamed a file `/Library/Python/2.7/site-packages/easy_install.pth` (strangely being used by the macports installed Python), which now allowed me to install `pyneuroml` and `libneuroml` without interfering with the macports installed packages using `pip install <package name> --user`. Now prepending `$HOME/Library/Python/2.7/bin` to `PATH` allowed me to run `pynml` without issues.

**Comment by pgleeson** [comment]
Thanks for this info @espenhgn. 

I've never been happy with the default env provided for Python on Mac, I used to mainly use Macports, but on my new 10.12.6 machine I've mainly used Homebrew. That works fine for most things apart from some issues with Python (sometimes the native Mac Python libraries were being used & there were not always the same versions of installed modules on there, etc.)

I've now installed Anaconda and that seems to solve all of the Python issues I'd been having and anything installed with pip under that has been fine (scripts go to $HOME/anaconda/bin).

**Comment by espenhgn** [comment]
Hi @pgleeson,
Yes, I've continued to use macports, for the most part it's just working well and leaves /usr/local alone (in contrast to Brew). But I see for a working Python environment that Anaconda offers some benefits over both. I use it, but now mostly for testing builds.

**Comment by sanjayankur31** [comment]
Closing. Please re-open if the issue persists.
