### ISSUE TITLE
pynml:execute_command_in_dir fails on Win 7

### ISSUE THREAD

**Issue by diegoflassa** [NeuroML/pyNeuroML#45]
Version : 0.3.1
Script: pynml.py
Func: execute_command_in_dir
OS: Windows 7 

Hy.

In a Windows 7 environment, when trying to use the 'pynml:execute_command_in_dir' function, i get the error

"Exception close_fds is not supported on Windows platforms"

This happens because of the param 'close_fds=True' in the 'subprocess.check_output' call.

If 'close_fds' is set to FALSE it runs successfully.
Note that 'close_fds=True' is hard coded in the method.

**Comment by pgleeson** [comment]
@diegoflassa have a look at the latest version, I've added some [options specific for running on Windows](https://github.com/NeuroML/pyNeuroML/commit/b710c24de25da7fa9b2ada749efa4d238bf00bac), and it seems to work on Win7 for me.

**Comment by diegoflassa** [comment]
Works Flawlessly! Thanks for the feedback.
