### ISSUE TITLE
Use of quantity as a plot title causes error in matplotlib.tight_layout

### ISSUE THREAD

**Issue by RastaMarcus** [NeuroML/pyNeuroML#54]
Hi, 

I have a project with c302 of openworm (https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302), using pyNeuroML.

The problem occurs as I add some variables, the gate activation rates, to be plotted. Because of the structure of the NeuroML file, the quantity attribute is very long (see an example of code below).

`<Line id="ADAL_k_slow_n" quantity="ADAL/0/GenericNeuronCell/biophys_GenericNeuronCell/membraneProperties/k_slow_all/k_slow/n/q" scale="1" color="#169445" timeScale="1ms"/>`

Now the problem is on line 819 of pynml.py, where the quantity attribute is used as title for the plot : 

`        for col in of.findall(ns_prefix+'OutputColumn'):
            quantity = col.attrib['quantity']
            traces[quantity] = []
            cols.append(quantity)`

The quantity attribute is so long that I get an error in matplotlib.tight_layout : "ValueError: left cannot be >= right"

Changing `quantity = col.attrib['quantity']` into `quantity = col.attrib['id']` solves the problem.
Is there a reason why the 'quality' attribute is used instead of the id ?

**Comment by pgleeson** [comment]
Hi @RastaMarcus,

The reason I believe is that there may be the same id used across different files (e.g. 'v0','v1') which get saved independently (the id is not present in the saved file, just data in columns).  Then when the reload_saved_data() loads these in, it needs a unique identifier for each to store in a dict, and the quantity is likely to be unique as it has the full path to the variable (which is unlikely to be present in multiple files, and even if it is, should be identical).

The point that you're having a problem seems to be the plotting inside reload_saved_data method. A better option for more control might be to not plot here, but use the returned dict 'traces', and plot whatever you need there using [pynml.generate_plot()](https://github.com/NeuroML/pyNeuroML/blob/master/examples/quick_plot.py)
