### ISSUE TITLE
Random123 seed error with python3.x syntax (simulator NEURON)

### ISSUE THREAD

**Issue by harshagurnani** [NeuroML/pyNeuroML#59]
I'm running biophysical network models after export to NEURON.

I was using *spikeGeneratorPoisson* for which a Random number generator is created/initialised in the exported neuron-python simulation file.
The generator is *Random123* with 3 numbers to define the stream: ( *id1, id2, id3* ) which are automatically set by the following piece of code:
```python
###############################################################################
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int

###############################################################################
    # Initialize the stim randomizer
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _init_stim_randomizer(self,rand, stimType, gid, seed): 
        #print("INIT STIM  %s; %s; %s; %s"%(rand, stimType, gid, seed))
        rand.Random123(self._id32(stimType), gid, seed)
```

The first number *id1* is created by passing the spikeGenerator population ID "*stimType*" through a hashing function.

Unfortunately, with Python 3.x, the string "stimType" is stored as Unicode and needs to be encoded as binary before passing to hash function.

I'm currently manually editing the generated simulation file by encoding the string:
```python
#######
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj.encode('utf-8')).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int

 ```

Is there a away to change the export code itself? This should be backward-compatible with Python 2.x (string can be bytestring or unicode)?

**Comment by pgleeson** [comment]
Thanks for the suggestion. It's fixed in the development branch here: https://github.com/NeuroML/org.neuroml.export/commit/bd243bd785680bb711776a081d6d16c901ff33fb. Rebuild from source and it should work for you, it will be in the binary release soon.
