### ISSUE TITLE
Warning, check 10007

### ISSUE THREAD

**Issue by BKriener** [NeuroML/pyNeuroML#62]
When converting a hoc file from the dentate gyrus basket cell files provided in 
https://senselab.med.yale.edu/ModelDB/showmodel.cshtml?model=140789#tabs-1
by Noerenberg et al.(2010) I receive a warning:

Warning, check: 10007 (Segment Groups should specify numberInternalDivisions in a <property> element as a child of <segmentGroup>) failed! ... SegmentGroup: axon_2249, has incorrect location for <property> for numberInternalDivisions (should be child of <segmentGroup>)

I which way do I have to worry about this?

Best,
Birgit

**Comment by pgleeson** [comment]
Quick response: you shouldn't have to worry about this, it's just a slightly older format for the metadata (nseg) from the conversion to NeuroML. As long as you have the latest versions of the jNeuroML/pyNeuroML libraries it should be fine. What is your specific workflow for conversions?

**Comment by BKriener** [comment]
I don't have the *very* latest (pyneuroml 0.3.11, with PyLEMS 0.4.9.1 and libNeuroML 0.2.39) , but can check with newer versions. I have no specific workflow apart from running 
export_to_neuroml2("test.hoc", "test.morphonly.cell.nml", includeBiophysicalProperties=False)
on the hoc files from modeldb.

**Comment by pgleeson** [comment]
Looking closer at this I see that the export by default adds the nseg/numberInternalDivisions info in **both** the old format and the new: 
```
  <segmentGroup id = "mainDendSec"  neuroLexId="sao864921383">
     <notes>This group contains an unbranched set of segments, and all of the segmentGroups marked with neuroLexId = sao864921383 form a non-overlapping set of all of the segments.
     These segmentGroups correspond to the 'cables' of NeuroML v1.8.1, and map to/from NEURON sections.</notes>
    <!-- This is currently inside (old convention) & outside (new convention) the <annotation> element, as some APIs have trouble reading what's inside <annotation> (<xs:any..> in Schema) -->
    <property tag="numberInternalDivisions" value="3"/> <!-- Discretization of model at time of export from NEURON. Can be overridden by importing application -->
    <annotation>
      <property tag="numberInternalDivisions" value="3"/> <!-- Discretization of model at time of export from NEURON. Can be overridden by importing application -->
    </annotation>
  ...
```

This maximizes compatibility with applications looking to read the file, but the `<property tag="numberInternalDivisions" ...>` is the preferred location for the info.
