### ISSUE TITLE
Make NML2ChannelAnalysis more modular

### ISSUE THREAD

**Issue by rgerkin** [NeuroML/pyNeuroML#7]
@pgleeson (Also see [this](https://github.com/VahidGh/ChannelWorm/issues/47))

NML2ChannelAnalysis.run() (implementing the old main(), now wrapped by main() in my [pull request](https://github.com/NeuroML/pyNeuroML/pull/6)) does too many things on one function.  Or rather, too much useful functionality, such as the display and saving of IV curves, is in main() rather than its own functions called by main().  So I'd like to refactor run() to call more functions that can in turn be used by scripts that don't want to use main() or run() as an entry point, but instead want to do things in pieces, for example SciUnit testing.

**Comment by pgleeson** [comment]
Sure, if you're happy to do this...

**Comment by rgerkin** [comment]
Done, in #8.
