### ISSUE TITLE
No such file or directory ": "

### ISSUE THREAD

**Issue by njhulst** [NeuroML/pyNeuroML#72]
Dear people,
I try to simulate my LEMS file with pynml.run_lems_with_jneuroml_neuron, but the error I get contains the message: 
FileNotFoundError: [Errno 2] No such file or directory: '': '' 
I can't figure out how to resolve this, I don't think I point to that file or directory anywhere in my code. 
My code and the full error message can be found here:
https://github.com/njhulst/IO-temperature-dependence/blob/master/%5BtemporaryFolder%5DcellTuning/CellTuning.ipynb 
I would be grateful if anyone could point me in the right direction!

**Comment by pgleeson** [comment]
I assume it's an issue with one of the paths that needs to be interpreted by python. There's a good chance that it's down to the use of [] in your folder name, I'd assume various things including python might not like " IO-temperature-ependence/[temporaryFolder]cellTuning/..." Can you try renaming that?

**Comment by njhulst** [comment]
Thank you for your response. There was indeed a problem with the path, the [] turned out not to be problematic, but I gave an empty path to the exec_in_dir variable.. problem solved now :)
