### ISSUE TITLE
`pynml-summary` does not list SynapticConnections and ExplicitInputs

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#73]
It shows Connections if they are in projections, and it shows Inputs in Input lists. Can it also show entities that aren't included in these groups?

**Comment by pgleeson** [comment]
Looking into this. It's actually to do with the helper methods added to the "off the shelf" generateDS generated API in libNeuroML: https://github.com/NeuralEnsemble/libNeuroML/blob/bbd0a2a545a08dfa784425e471bb079b436143d4/neuroml/nml/helper_methods.py#L601

**Comment by pgleeson** [comment]
Added in development
