### ISSUE TITLE
Allow `-lems-graph` to also handle LEMS files

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#74]
If a LEMS file is passed as an argument, we call `jnml -graph` to generate the LEMS graph. If a nml file is passed, we process it normally.

**Comment by sanjayankur31** [comment]
@pgleeson : I cant seem to assign it to myself. Could you do it when you have a minute please?

**Comment by pgleeson** [comment]
@sanjayankur31 This repo has just been added to the list of those you can maintain, so you should be able to self assign etc. now.

**Comment by sanjayankur31** [comment]
> @sanjayankur31 This repo has just been added to the list of those you can maintain, so you should be able to self assign etc. now.

Hrm, still not able to assign tickets to myself etc. Could you double-check the teams/settings once when you have a minute please?

**Comment by pgleeson** [comment]
It should be fixed now...

**Comment by sanjayankur31** [comment]
Yeh, works now! Thanks! The PR was merged, so closing this too.
