### ISSUE TITLE
Error installing mock

### ISSUE THREAD

**Issue by travs** [NeuroML/pyNeuroML#9]
Not sure why this is happening since I don't see `mock` in the setup.py or requirements.txt files, but I get the following error when I try to run `python setup.py install` in a fresh venv.

OS X 10.10

```
Processing dependencies for pyNeuroML==0.1.1
Searching for mock
Reading https://github.com/purcell/airspeed.git
Reading https://pypi.python.org/simple/mock/
Best match: mock 1.3.0
Downloading https://pypi.python.org/packages/source/m/mock/mock-1.3.0.tar.gz#md5=73ee8a4af
b3ff4da1b4afa287f39fdeb
Processing mock-1.3.0.tar.gz
Writing /var/folders/nk/0qlyp_m90hg83g473tx9hg580000gn/T/easy_install-HmuL_w/mock-1.3.0/se
tup.cfg
Running mock-1.3.0/setup.py -q bdist_egg --dist-dir /var/folders/nk/0qlyp_m90hg83g473tx9hg
580000gn/T/easy_install-HmuL_w/mock-1.3.0/egg-dist-tmp-hxCk0o
mock requires setuptools>=17.1. Aborting installation
error: Setup script exited with 1
```

**Comment by pgleeson** [comment]
Not sure why that's being included either, though the end of the error message suggests updating setuptools might solve the problem.

**Comment by rgerkin** [comment]
@travs What dependency of pyNeuroML has mock as a dependency?

**Comment by travs** [comment]
@rgerkin I'm not sure. None of the dependencies of pyNeuroML seem to, except [maybe](https://github.com/matplotlib/matplotlib/issues/3649) `matplotlib`, though I'm not certain about that one.
Anyway, I was able to get past this by doing `pip install mock` manually, without changing anything else.
