### ISSUE TITLE
Brian 2 simulation appears to be incompletely implemented

### ISSUE THREAD

**Issue by jonrkarr** [NeuroML/pyNeuroML#97]
**Describe the bug**
Brian 2 simulation fails due to a missing module at [`pyneuroml/pynml.py#L948`](https://github.com/NeuroML/pyNeuroML/blob/master/pyneuroml/pynml.py#L948)

**To Reproduce**
```python
import pyneuroml.pynml
pyneuroml.pynml.run_lems_with_jneuroml_brian2('tests/fixtures/LEMS_NML2_Ex5_DetCell.xml')
```

**Expected behavior**
Work as advertised

**Observed behavior**
```sh
~/.local/lib/python3.9/site-packages/pyneuroml/pynml.py in run_lems_with_jneuroml_brian2(lems_file_name, paths_to_include, max_memory, skip_run, nogui, load_saved_data, reload_events, plot, show_plot_already, exec_in_dir, verbose, exit_on_fail, cleanup)
    946             exit_on_fail=exit_on_fail)
    947         print('oooooo')
--> 948         import LEMS_SimFNTest_brian2
    949         print('eeee')
    950 

ModuleNotFoundError: No module named 'LEMS_SimFNTest_brian2'
```

**System information:**
 - OS: Ubuntu
 - Python version: 3.9.5
 - Version of tools in use: 0.5.11

**Additional context**

**Comment by pgleeson** [comment]
Thanks @jonrkarr . Yes that was experimental code committed too early. Fixed in https://github.com/NeuroML/pyNeuroML/commit/7f4bc2d924a2ca2a35b7707eec28d19e6fdba3eb
